### ISSUE TITLE
Allow Vector constraints

### ISSUE THREAD

**Issue by joaquimg** [joaquimg/BilevelJuMP.jl#5]
Example: `@constraint(model, con, A * x .== b)`

**Comment by NLaws** [comment]
@joaquimg nice work on the v0.1.0 release! I'm excited to see this package progressing and will be using it soon to solve some problems. Just curious if this issue is still open? Thought maybe it was fixed with the dispatch on `Union{JuMP.ScalarConstraint{F,S},JuMP.VectorConstraint{F,S}}` in your extension of `JuMP.add_constraint` [here](https://github.com/joaquimg/BilevelJuMP.jl/blob/64be3f06f2db7e7bc5451bc3452c50a0e0699a37/src/jump.jl#L509)?

**Comment by joaquimg** [comment]
@NLaws glad that you liked, I haven't tested. That's why I have not closed, I will test asap.

**Comment by joaquimg** [comment]
you are correct, this is solved, and tests were added in #52
