### ISSUE TITLE
Possible readibility/usage improvement: simplify notation of FortunyAmatMcCarl reformulation

### ISSUE THREAD

**Issue by davide-f** [joaquimg/BilevelJuMP.jl#75]
Dear Developers,

I may suggest the developers a reformulation of the names of set/get_primal_upper/lower_bound_hint and get/set_dual_upper/lower_bound in a maybe more straightforward formulation such as set/get_(FAMC)bound or similar with maybe the optional values upper/lower or both to specify the bound to set. I think it may be simpler to use and also to describe in the documentation.

From the code point of view, the changes should be limited. I may try to propose a version if I have time and you agree on the point.

**Comment by joaquimg** [comment]
These should be available in other formulation other than FAMC, because they are a way to strengthen bounds without creating constraints that will be dualized (and therefore generate more constraints).
The dual bounds and not only hints because the are used to set bounds on dual variables without the need to use DualOf.
These bounds are used in binary expansions for example.
I am open for suggestions and renaming though!
PR welcome.

**Comment by joaquimg** [comment]
closing due incativity
